In [1]:
import numpy as np 

"""
1.Write a NumPy program to create an array of 10 zeros, array of 10 ones, and
array of 10 fives.
"""
zerose_arr = np.zeros(10)
ones_arr = np.ones(10)
fives_arr = np.full(10, 5)
print(zerose_arr)
print(ones_arr)
print(fives_arr)

"""
2. Write a NumPy program to create an array of all even integers from 30 to
70.
"""

even_integers = np.arange(30, 71, 2)
print(even_integers)
"""
3.Write a NumPy program to create an array of given shape (5,6) and integer
type, filled with zeros.
"""
arr56 = np.zeros((5, 6), dtype=int)
print(arr56)

"""
4.Create a 10x10 array with random values and find the minimum and
maximum values.
"""
random_array = np.random.rand(10, 10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print(f"arr {random_array}" )
print( f"max is  {max_value}")
print( f"min is  {min_value}" )

"""
  5. Write a NumPy program to create a 3x3 array with values ranging from 2 to
10.
"""
random_array = np.arange(2, 11).reshape(3, 3)
random_array

"""
6.Write a NumPy program to create an array of size = 20 using arrange, then
extract all numbers from a given array greater than 15.
"""
arr = np.arange(20)
greater_than_15 = arr[arr > 15]
print(greater_than_15)

"""
7. Write a NumPy program to combine the two 2-dimensional arrays using
hstack and vstack.
Array 1: [[0, 1, 3], [5, 7, 9]]
Array 2: [[0, 2, 4], [6, 8, 10]]

"""
array1 = np.array([[0, 1, 3], [5, 7, 9]])
array2 = np.array([[0, 2, 4], [6, 8, 10]])

hstacked = np.hstack((array1, array2))
vstacked = np.vstack((array1, array2))

print( hstacked)
print( vstacked)

"""
8. Write a NumPy program to create ones array of size 10 and change the 6th
element to 11.


"""
ones_array = np.ones(10)
ones_array[5] = 11
 
"""
9. Write a NumPy program to append a value to the end of an array.
"""
array = np.array([1, 2, 3])
appended_array = np.append(array, 4)

"""
10.Write a NumPy program to reverse an array [using two different methods].
"""
arr = np.array([1, 2, 3, 4, 5])
reversed_array = np.array([])
for i in range(len(arr) - 1, -1, -1):
    reversed_array = np.append(reversed_array, arr[i])

print(reversed_array)

arr= np.array([1, 2, 3, 4, 5])
reversed_array = arr[::-1] 
#reversed_array = arr[4::-1] from end to start step -1
print(reversed_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 5 5 5 5 5 5 5 5 5]
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
arr [[0.90819949 0.97278626 0.15337594 0.17720703 0.23879645 0.52414464
  0.98165445 0.23002668 0.10727228 0.91429632]
 [0.06765607 0.65362188 0.78639499 0.12743322 0.92753227 0.14489728
  0.48051872 0.66402341 0.56112543 0.07536355]
 [0.79934225 0.62181867 0.72012508 0.68017374 0.36983765 0.92629129
  0.4361598  0.92377386 0.33501125 0.67201383]
 [0.93070173 0.79716429 0.60855448 0.97586471 0.78666612 0.52068577
  0.97164411 0.34622842 0.94934541 0.99763855]
 [0.41232475 0.71461216 0.09950702 0.51423936 0.15321518 0.81287501
  0.0790944  0.22878649 0.81496583 0.25644998]
 [0.91546233 0.31617615 0.94594943 0.7187136  0.59423842 0.88212272
  0.17634825 0.81568298 0.27174158 0.41102643]
 [0.95989647 0.84430228 0.3312285  0.57925823 0.69391816 0.17520835
  0.4991746

In [1]:
import numpy as np
vector1 = np.array([1,2,3,4,5,6,7,8,9])
vector1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])