## Linear Combination
### Use NumPy

$$v_1=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix},
v_2=\begin{bmatrix} 3 \\ 5 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 0 \\ 0 \\ 8 \end{bmatrix}$$
- Find <b>b</b> vector where $$b=3v_1+0v_2+0v_3$$
- Find <b>x</b> vector where $$x=-v_1+v_2-0.5v_3$$

In [2]:
import numpy as np
import sympy as sp

In [2]:
v1=np.array([[1],[2],[3]])
v2=np.array([[3],[5],[1]])
v3=np.array([[0],[0],[8]])
b=3*v1+0*v2+0*v3
b

array([[3],
       [6],
       [9]])

In [3]:
x=-1*v1+v2-0.5*v3
x

array([[ 2.],
       [ 3.],
       [-6.]])

b:
[[3]
 [6]
 [9]]

x:
[[ 2.]
 [ 3.]
 [-6.]]


## Vector Span
### Use Numpy (matrix inverse) and SymPy (rref)

#### Is $$v=\begin{bmatrix} 19 \\ 10 \\ -1 \end{bmatrix}$$ in the span of
$$v_1=\begin{bmatrix} 3 \\ -1 \\ 2 \end{bmatrix},
v_2=\begin{bmatrix} -5 \\ 0 \\ 1 \end{bmatrix},
v_3=\begin{bmatrix} 1 \\ 7 \\ -4 \end{bmatrix}$$

In [11]:
v_matrix=sp.Matrix([[3,-5,1,19],[-1,0,7,10],[2,1,-4,-1]])
rref,pivot=v_matrix.rref()
print(rref)
print(pivot)

Matrix([[1, 0, 0, 4], [0, 1, 0, -1], [0, 0, 1, 2]])
(0, 1, 2)


(Matrix([
 [1, 0, 0,  4],
 [0, 1, 0, -1],
 [0, 0, 1,  2]]),
 (0, 1, 2))

In [13]:
v_vector=np.array([[19],[10],[-1]])
v_matrix=np.array([[3,-5,1],[-1,0,7],[2,1,-4]])
v_inv=np.linalg.inv(v_matrix)
x=v_inv@v_vector
x

array([[ 4.],
       [-1.],
       [ 2.]])

[[ 4.]
 [-1.]
 [ 2.]]


## Vector Linear Independence
### Use rref and determinant
- Consider the following sets of vectors in R3. If the set is independent, prove it.
- If the set is dependent, find a nontrivial linear combination of the vectors which is equal to 0.
    - {(2, 0, -3), (1, 1, 1), (1, 7, 2)}.
    - {(1, 2, -1), (4, 1, 3), (-10, 1, -11)}.

<b>Hint: we have to determine whether this implies that 𝒂=𝒃=𝒄=𝟎.</b>

In [14]:
M = sp.Matrix([[2, 0, -3],
               [1, 1, 1],
               [1, 7, 2]])
rref,pivot=M.rref()
print(rref)
print(pivot)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
(0, 1, 2)


(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [15]:
M = sp.Matrix([[1, 2, -1],
               [4, 1, 3],
               [-10, 1, -11]])
rref,pivot=M.rref()
print(rref)
print(pivot)

Matrix([[1, 0, 1], [0, 1, -1], [0, 0, 0]])
(0, 1)


(Matrix([
 [1, 0,  2],
 [0, 1, -3],
 [0, 0,  0]]),
 (0, 1))

0

## Linear Transformation
### Ex.1

$$T=\begin{bmatrix} 1&2 \\ 3&7 \end{bmatrix}$$
- Write the linear transformation expression of this matrix. i.e. Linear functions of x,y.
- Apply the transformation matrix <b>T</b> to the following vectors:
$$\begin{bmatrix} 1 \\ 0 \end{bmatrix},\begin{bmatrix} 0 \\ 1 \end{bmatrix} $$
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(1,0)</b>

In [8]:
T=np.array([[1,2],[3,7]])
x=np.array([[1],[0]])
T@x

array([[1],
       [3]])

In [9]:
y=np.array([[0],[1]])
T@y

array([[2],
       [7]])

A.v1=
[[1]
 [3]]

A.v2=
[[2]
 [7]]


(x,y):
[[ 7.]
 [-3.]]


### Ex.2
### For the expression $$T\begin{bmatrix} x \\ y \end{bmatrix}=\begin{bmatrix} x+y \\ y \end{bmatrix}$$
- Find the transformation matrix.
- Represent the transformation graphically <b>(on paper)</b>.
- Find all points <b>(x,y)</b> such that <b>T(x,y)=(3,4)</b>

In [16]:
T = np.array([[1, 1], [0, 1]])
b = np.array([3, 4])
T_inv = np.linalg.inv(T)
T_inv @ b

array([-1.,  4.])

x:
[[-1.]
 [ 4.]]


## Determinant
### Find Determinant of:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$


In [17]:
x=np.array([[3,8],[4,6]])
np.linalg.det(x)




-14.000000000000004

In [18]:
y=np.array([[4,6],[3,8]])
np.linalg.det(y)

14.000000000000004

In [19]:
z=np.array([[6,1,1],[4,-2,5],[2,8,7]])
np.linalg.det(z)

-306.0

In [20]:
m=np.array([[3,2,0,1],[4,0,1,2],[3,0,2,1],[9,2,3,1]])
np.linalg.det(m)

24.000000000000004

## Matrix Rank
### Find the rank of the matrix (use rref and confirm using matrix_rank())

$$X = \begin{bmatrix} 1&2&4&4 \\ 3&4&8&0 \end{bmatrix}$$
$$Y = \begin{bmatrix} 1&2&3 \\ 2&3&5 \\ 3&4&7 \\ 4&5&9  \end{bmatrix}$$

In [25]:
x=sp.Matrix([[1,2,4,4],[3,4,8,0]])
rref,pivot=x.rref()
print(rref)
print(pivot)
print(f"X rank : {len(pivot)}")

Matrix([[1, 0, 0, -8], [0, 1, 2, 6]])
(0, 1)
X rank : 2


In [26]:
y=sp.Matrix([[1,2,3],[2,3,5],[3,4,7],[4,5,9]])
rref,pivot=y.rref()
print(rref)
print(pivot)
print(f"y rank : {len(pivot)}")

Matrix([[1, 0, 1], [0, 1, 1], [0, 0, 0], [0, 0, 0]])
(0, 1)
y rank : 2


(Matrix([
[1, 0, 0, -8],
[0, 1, 2,  6]]), (0, 1))

X rank: 2


(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0]]), (0, 1))

Y rank: 2


## Matrix Inverse
### Find the inverse:

$$\begin{bmatrix} 3&8 \\ 4&6 \end{bmatrix} , \begin{bmatrix} 4&6 \\ 3&8 \end{bmatrix}$$
$$\begin{bmatrix} 6&1&1 \\ 4&-2&5 \\ 2&8&7\end{bmatrix}$$
$$\begin{bmatrix} 3&2&0&1 \\ 4&0&1&2 \\ 3&0&2&1 \\ 9&2&3&1\end{bmatrix}$$

In [27]:
x=np.array([[3,8],[4,6]])
np.linalg.inv(x)

array([[-0.42857143,  0.57142857],
       [ 0.28571429, -0.21428571]])

In [28]:
y=np.array([[4,6],[3,8]])
np.linalg.inv(y)

array([[ 0.57142857, -0.42857143],
       [-0.21428571,  0.28571429]])

In [29]:
z=np.array([[6,1,1],[4,-2,5],[2,8,7]])
np.linalg.inv(z)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [30]:
m=np.array([[3,2,0,1],[4,0,1,2],[3,0,2,1],[9,2,3,1]])
np.linalg.inv(m)

array([[-0.25      ,  0.25      , -0.5       ,  0.25      ],
       [ 0.66666667, -0.5       ,  0.5       , -0.16666667],
       [ 0.16666667, -0.5       ,  1.        , -0.16666667],
       [ 0.41666667,  0.25      ,  0.5       , -0.41666667]])

1.
 [[-0.42857143  0.57142857]
 [ 0.28571429 -0.21428571]]

2.
 [[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]

3.
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

4.
 [[-0.25        0.25       -0.5         0.25      ]
 [ 0.66666667 -0.5         0.5        -0.16666667]
 [ 0.16666667 -0.5         1.         -0.16666667]
 [ 0.41666667  0.25        0.5        -0.41666667]]


## Changing Basis (Orthogonal Coordinates)
### Perform the following (Once by dot product and another by matix).
### First confirm b1 and b2 are orthogonal basis.

### 1) Transform $v=\begin{bmatrix}5 \\ -1\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}1 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\-1\end{bmatrix}$
### 2) Transform $v=\begin{bmatrix}10\\-5\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}3\\ 4\end{bmatrix}$ , $b_2=\begin{bmatrix} 4 \\-3 \end{bmatrix}$

In [42]:
b=np.array([[1,1],[1,-1]])
transform=np.array([[5],[-1]])
b1=(np.dot(transform.T,b[0]))/(np.linalg.norm(b[0])**2)
b2=(np.dot(transform.T,b[1]))/(np.linalg.norm(b[1])**2)
np.array([[b1],[b2]])

array([[[2.]],

       [[3.]]])

In [43]:
np.linalg.inv(b)@transform

array([[2.],
       [3.]])

In [ ]:
# Ex. 1 Using dot product


Using dot product
vb:
[[2.]
 [3.]]


In [40]:
b=np.array([[3,4],[4,-3]])
transform=np.array([[10],[-5]])
b1=(np.dot(transform.T,b[0]))/(np.linalg.norm(b[0])**2)
b2=(np.dot(transform.T,b[1]))/(np.linalg.norm(b[1])**2)
np.array([[b1],[b2]])

array([[[0.4]],

       [[2.2]]])

In [41]:
np.linalg.inv(b)@transform

array([[0.4],
       [2.2]])

In [ ]:
# Ex. 1 Using transformation matrix


Using transformation matrix
vb:
[[2.]
 [3.]]


In [ ]:
# Ex. 2 Using dot product


Using dot product
vb:
[[0.4]
 [2.2]]


In [ ]:
# Ex. 2 Using transformation matrix


Using transformation matrix
vb:
[[0.4]
 [2.2]]


## Changing Basis (Non-Orthogonal Coordinates)
### Perform the following.
### First confirm b1 and b2 are non-orthogonal basis.

### - Transform $v=\begin{bmatrix}5 \\ 2\end{bmatrix}$ from the stadard basis to b1 and b2 basis. $b_1=\begin{bmatrix}3 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\1\end{bmatrix}$


In [45]:
b=np.array([[3,1],[1,1]])
b_inv=np.linalg.inv(b)
transform=np.array([[5],[2]])
b_inv@transform

array([[1.5],
       [0.5]])

vb:
[[1.5]
 [0.5]]


## Transformation in Non-Orthonormal Space
### - For $R^2$ defined by the basis basis. $b_1=\begin{bmatrix}3 \\ 1\end{bmatrix}$ , $b_2=\begin{bmatrix}1\\1\end{bmatrix}$
### - Find the transformation matrix in B coordinate system for the following transformations:
#### 1- Reflection around x-axis $T=\begin{bmatrix} 1&0 \\ 0&-1\end{bmatrix}$
#### 2- Rotation matrix $T=\begin{bmatrix} 0&1 \\ -1&0\end{bmatrix}$
### - Apply these transformation to the vector  $v_b=\begin{bmatrix}1.5 \\ 0.5\end{bmatrix}$

In [48]:
b=np.array([[3,1],[1,1]])
transform=np.array([[1,0],[0,-1]])
b_inv=np.linalg.inv(b)
v=np.array([[1.5],[.5]])
b_inv@transform@b@v

array([[ 3.5],
       [-5.5]])

In [49]:
b=np.array([[3,1],[1,1]])
transform=np.array([[0,1],[-1,0]])
b_inv=np.linalg.inv(b)
v=np.array([[1.5],[.5]])
b_inv@transform@b@v

array([[ 3.5],
       [-8.5]])

TB1 =
 [[ 2.  1.]
 [-3. -2.]]

TB2 =
 [[ 2.  1.]
 [-5. -2.]]

vb_TB1 =
 [[ 3.5]
 [-5.5]]

vb_TB2 =
 [[ 3.5]
 [-8.5]]


## Gram–Schmidt Process (Orthogonalization)
### Apply Gram-Shmidt process for the following sequence in vectors in $R^3$:
### $$\begin{bmatrix}1 \\2\\ 0\end{bmatrix} , \begin{bmatrix}8 \\1\\ -6\end{bmatrix} , \begin{bmatrix}0 \\0\\ 1\end{bmatrix}$$
#### Confirm your answer using numpy.linalg.qr() function
#### Make sure all vectors given above are basis in $R^3$ space.
#### Confirm that the orthogonal matrix has orthonormal vectors.
#### Confirm that the transpose of the orthogonal matrix is it's inverse.
#### Reflect the vector r = (1,3,4) arround the xy plane containing the two vectors $\begin{bmatrix}1 \\2\\ 0\end{bmatrix} , \begin{bmatrix}8 \\1\\ -6\end{bmatrix}$.
#### Round all results to 3 decimal points.

In [98]:
v=np.array([[1,2,0],
             [8,1,-6],
             [0,0,1]])
np.linalg.det(v).round()

-15.0

In [95]:
v1=v[0]
u1=v1
u1

array([1, 2, 0])

In [96]:
v2=v[1]
u2=(v2-(np.dot(v1,v2))/(np.linalg.norm(v1)**2)*v1)
u2/=np.linalg.norm(u2)
u2

array([ 0.66666667, -0.33333333, -0.66666667])

In [97]:
v3=v[2]
u3=v3-(np.dot(v1,v3))/(np.linalg.norm(v1)**2)*v1-(np.dot(u2,v3))/(np.linalg.norm(u2)**2)*u2
u3/=np.linalg.norm(u3)
u3

array([ 0.59628479, -0.2981424 ,  0.74535599])

In [101]:
np.linalg.qr(v)

QRResult(Q=array([[-0.12403473, -0.99227788,  0.        ],
       [-0.99227788,  0.12403473,  0.        ],
       [-0.        ,  0.        ,  1.        ]]), R=array([[-8.06225775, -1.24034735,  5.95366726],
       [ 0.        , -1.86052102, -0.74420841],
       [ 0.        ,  0.        ,  1.        ]]))

In [102]:
ref,pivot=sp.Matrix(v).rref()
print(ref)
print(pivot)

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
(0, 1, 2)


In [103]:
v1=v[0]
v2=v[1]
p=np.array([1,3,4])
u1=v1
u2=(v2-(np.dot(v1,v2))/(np.linalg.norm(v1)**2)*v1)
u2/=np.linalg.norm(u2)
ref= p - 2 * (p - (u1 + u2))
ref

array([ 2.33333333,  0.33333333, -5.33333333])

det(V): -15.0
Mrref:
 (Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


u1:
[[1]
 [2]
 [0]]

u2:
[[ 6.]
 [-3.]
 [-6.]]

u3:
[[ 0.44444444]
 [-0.22222222]
 [ 0.55555556]]

e1:
[[0.4472136 ]
 [0.89442719]
 [0.        ]]

e2:
[[ 0.66666667]
 [-0.33333333]
 [-0.66666667]]

e3:
[[ 0.59628479]
 [-0.2981424 ]
 [ 0.74535599]]


Using QR:
[[-0.4472136   0.66666667  0.59628479]
 [-0.89442719 -0.33333333 -0.2981424 ]
 [-0.         -0.66666667  0.74535599]]


1.0

Q Inverse:
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]
Q Transpose
 [[-0.447 -0.894 -0.   ]
 [ 0.667 -0.333 -0.667]
 [ 0.596 -0.298  0.745]]


Transformation matrix in the non-orthonormal basis:
[[ 0.28888889  0.35555556 -0.88888889]
 [ 0.35555556  0.82222222  0.44444444]
 [-0.88888889  0.44444444 -0.11111111]]

Transformed vector:
[[-2.2]
 [ 4.6]
 [ 0. ]]


![image.png](attachment:image.png)

# Quiz 1
![image-2.png](attachment:image-2.png)

In [51]:
mat=sp.Matrix([(1,0,0,4),(0,1,0,7),(0,0,1,-1)])
print(mat)
rref,pivot=mat.rref()
print(rref)
print(pivot)
print("span")

Matrix([[1, 0, 0, 4], [0, 1, 0, 7], [0, 0, 1, -1]])
Matrix([[1, 0, 0, 4], [0, 1, 0, 7], [0, 0, 1, -1]])
(0, 1, 2)
span


In [55]:
mat=sp.Matrix([
    [4, 1, 0],
    [5, 2, 1]  ])
rref,pivot=mat.rref()
print(rref)
print(pivot)
print("dependent")

Matrix([[1, 0, -1/3], [0, 1, 4/3]])
(0, 1)
dependent


In [56]:
mat=sp.Matrix([
    [1, 0, 0],
    [0, 1, 2],
    [0, 0, 1]])
rref,pivot=mat.rref()
print(rref)
print(pivot)
print("independent")

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
(0, 1, 2)
independent


In [57]:
mat=np.eye(4)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [60]:
b=np.array([[4.5,-0.5],[-2.5,0.5]])
v=np.array([[1],[3]])
b@v

array([[ 3.],
       [-1.]])

# Quiz 2
![image-3.png](attachment:image-3.png)

In [62]:
mat=np.array([[1,0],[0,-1]])
rot=np.array([[1],[1]])
mat@rot

array([[ 1],
       [-1]])

In [63]:
sh=np.array([[1,0],[0,5]])
mat@sh@rot

array([[ 1],
       [-5]])

# Quiz 3
![image-4.png](attachment:image-4.png)

In [66]:
mat=np.array([(2,-1),(3,-5)])
print(f'det : {np.linalg.det(mat)}')
print(f'inv : {np.linalg.inv(mat)}')

det : -6.999999999999999
inv : [[ 0.71428571 -0.14285714]
 [ 0.42857143 -0.28571429]]


In [64]:
mat=np.array([(1,3,-2),(0,1,4),(0,1,1)])
print(f'det : {np.linalg.det(mat)}')
print(f'inv : {np.linalg.inv(mat)}')

det : -3.0000000000000004
inv : [[ 1.          1.66666667 -4.66666667]
 [ 0.         -0.33333333  1.33333333]
 [-0.          0.33333333 -0.33333333]]


In [65]:
mat=np.array([(12,3,1),(2,0,2),(18,0,1)])
print(f'det : {np.linalg.det(mat)}')
print(f'inv : {np.linalg.inv(mat)}')

det : 102.00000000000004
inv : [[ 0.         -0.02941176  0.05882353]
 [ 0.33333333 -0.05882353 -0.21568627]
 [ 0.          0.52941176 -0.05882353]]


In [67]:
mat=np.array([(1,2,3),(3,6,9)])
print(f'det : {np.linalg.det(mat)}')
print(f'inv : {np.linalg.inv(mat)}')

LinAlgError: Last 2 dimensions of the array must be square

# Homework 1
![image-5.png](attachment:image-5.png)

In [68]:
mat=sp.Matrix([[1,0,2,-5],[-2,5,0,11],[2,5,8,8]])
rref,pivot=mat.rref()
print(rref)
print(pivot)
print("linear combination")

Matrix([[1, 0, 2, 0], [0, 1, 4/5, 0], [0, 0, 0, 1]])
(0, 1, 3)
linear combination


In [69]:
mat=sp.Matrix([[1,0,1,2],[1,2,2,1],[0,1,2,1]])
rref,pivot=mat.rref()
print(rref)
print(pivot)
print("linear combination")

Matrix([[1, 0, 0, 1], [0, 1, 0, -1], [0, 0, 1, 1]])
(0, 1, 2)
linear combination


In [70]:
mat=sp.Matrix([[1,1,0],[0,2,1],[1,2,2],[2,1,1]])
rref,pivot=mat.rref()
print(rref)
print(pivot)
print("dependent")

Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 0, 0]])
(0, 1, 2)
dependent


# Homework 2
![image-6.png](attachment:image-6.png)

In [74]:
mat1=np.array([[0,2,-1],[3,1,1],[0,-1,-2]])
mat

array([[ 1,  0,  0],
       [-1,  1,  0],
       [ 1,  2, -1]])

In [75]:
mat2=np.array([[1,0,0],[-1,1,0],[1,2,-1]])
mat

array([[ 1,  0,  0],
       [-1,  1,  0],
       [ 1,  2, -1]])

In [76]:
mat1@mat2

array([[-3,  0,  1],
       [ 3,  3, -1],
       [-1, -5,  2]])

In [77]:
mat=np.array([[1,1],[1,-1]])
np.linalg.inv(mat)

array([[ 0.5,  0.5],
       [ 0.5, -0.5]])

In [78]:
mat=np.array([[1,2],[3,5]])
np.linalg.inv(mat)

array([[-5.,  2.],
       [ 3., -1.]])

In [79]:
mat=np.array([[1,0,1],[0,1,1],[1,1,1]])
np.linalg.inv(mat)

array([[ 0., -1.,  1.],
       [-1.,  0.,  1.],
       [ 1.,  1., -1.]])

# Homework 3
![image-7.png](attachment:image-7.png)

In [80]:
mat=sp.Matrix([[0,1,1,1],[2,-1,2,0],[1,0,0,0],[0,0,-1,1]])
rref,pivot=mat.rref()
print(rref)
print(pivot)

Matrix([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
(0, 1, 2, 3)


In [84]:
v1=np.array([0,2,1,0])
v2=np.array([1,-1,0,0])
v3=np.array([1,2,0,-1])
v4=np.array([1,0,0,1])
u1=v1
u1=u1/np.linalg.norm(u1)
u1

array([0.        , 0.89442719, 0.4472136 , 0.        ])

In [86]:
u2=(v2-(np.dot(u1,v2))/(np.linalg.norm(u1)**2)*u1)
u2/=np.linalg.norm(u2)
u2

array([ 0.91287093, -0.18257419,  0.36514837,  0.        ])

In [87]:
u3=v3-(np.dot(u1,v3))/(np.linalg.norm(u1)**2)*u1-(np.dot(u2,v3))/(np.linalg.norm(u2)**2)*u2
u3/=np.linalg.norm(u3)
u3

array([ 0.31622777,  0.31622777, -0.63245553, -0.63245553])

In [88]:
u4=v4-(np.dot(u1,v4))/(np.linalg.norm(u1)**2)*u1-(np.dot(u2,v4))/(np.linalg.norm(u2)**2)*u2-(np.dot(u3,v4))/(np.linalg.norm(u3)**2)*u3
u4/=np.linalg.norm(u4)
u4

array([ 0.25819889,  0.25819889, -0.51639778,  0.77459667])